"""Where everything is, now that the site's source lives inside the repository.

    <repo>/                     REPO   the checkout these scripts read
      docs/img/*.png                   screenshots build_assets.py resizes
      docs/lespirant/                  the sponsor photograph
      seed/activity_logs.db            the sample logs the demo ships
      favicon.svg                      copied verbatim to the site
      site/                     SITE   the site's authored source, tracked
        index.html 404.html            the two real pages
        robots.txt sitemap.xml llms.txt
        assets/css/site.css            authored by hand
        assets/img/                    GENERATED by build_assets.py and
                                       build_og_card.py — but tracked anyway, so
                                       that site/index.html opens from a fresh
                                       clone with its images intact
        app/index.html                 a placeholder; the real demo is exported
        tools/                         these scripts
        _build/                 BUILD  the assembled site, gitignored

These paths used to be resolved against a gh-pages worktree root, with the
source checkout located by a `--main` argument. The scripts now live inside the
checkout they read, so both collapse into one relative walk up from __file__ —
there is nothing left for the caller to get wrong.
"""

from pathlib import Path

TOOLS = Path(__file__).resolve().parent
SITE = TOOLS.parent
REPO = SITE.parent
BUILD = SITE / "_build"
